version: "3.9"

services:

  backend:
    build: ./
    container_name: guane-intern-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - 'mongo'
    environment:
      MONGO_DETAILS: mongodb://mongo:27017
      SECRET_KEY: mgRx7MeJswEboDcVZ9xE1moMDhkUMdF0r
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      API_DOG_IMAGE: https://dog.ceo/api/breeds/image/random

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes: 
      - data:/data/db

volumes:
  data: